# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23fb279f0c3063bb728748361fbb096df357c853a1af54c99055d19908d25c854612f565f9ded8957d11ae1a7bcd5184dde1c3035dbd86f74dc72749e3f0da5a

test:
  secret_key_base: d4daa47fb6e3846f6ebe7cdc8b856e42e9fc58c2b7e049d15133d74c9e68d31626173f4333a822f4edb5c2abd04dedb05bef54d7ab4256486c589de6a6be6d23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
